require "./ical_value"

@[Link("ical")]
lib LibIcal
  enum IcalPropertyKind
    ICAL_ANY_PROPERTY = 0
    ICAL_ACTION_PROPERTY =1
    ICAL_ALLOWCONFLICT_PROPERTY =2
    ICAL_ATTACH_PROPERTY =3
    ICAL_ATTENDEE_PROPERTY =4
    ICAL_CALID_PROPERTY =5
    ICAL_CALMASTER_PROPERTY =6
    ICAL_CALSCALE_PROPERTY =7
    ICAL_CARID_PROPERTY =8
    ICAL_CATEGORIES_PROPERTY =9
    ICAL_CLASS_PROPERTY = 10
    ICAL_COMMENT_PROPERTY = 11
    ICAL_COMPLETED_PROPERTY = 12
    ICAL_CONTACT_PROPERTY = 13
    ICAL_CREATED_PROPERTY = 14
    ICAL_DATEFORMAT_PROPERTY = 15
    ICAL_DECREED_PROPERTY = 16
    ICAL_DEFAULTCHARSET_PROPERTY = 17
    ICAL_DEFAULTLOCALE_PROPERTY = 18
    ICAL_DEFAULTTZID_PROPERTY = 19
    ICAL_DESCRIPTION_PROPERTY = 20
    ICAL_DTEND_PROPERTY = 21
    ICAL_DTSTAMP_PROPERTY = 22
    ICAL_DTSTART_PROPERTY = 23
    ICAL_DUE_PROPERTY = 24
    ICAL_DURATION_PROPERTY = 25
    ICAL_EXDATE_PROPERTY = 26
    ICAL_EXPAND_PROPERTY = 27
    ICAL_EXRULE_PROPERTY = 28
    ICAL_FREEBUSY_PROPERTY = 29
    ICAL_GEO_PROPERTY = 30
    ICAL_GRANT_PROPERTY = 31
    ICAL_LASTMODIFIED_PROPERTY = 32
    ICAL_LOCATION_PROPERTY = 33
    ICAL_MAXRESULTS_PROPERTY = 34
    ICAL_MAXRESULTSSIZE_PROPERTY = 35
    ICAL_METHOD_PROPERTY = 36
    ICAL_ORGANIZER_PROPERTY = 37
    ICAL_OWNER_PROPERTY = 38
    ICAL_PERCENTCOMPLETE_PROPERTY = 39
    ICAL_PRIORITY_PROPERTY = 40
    ICAL_PRODID_PROPERTY = 41
    ICAL_QUERY_PROPERTY = 42
    ICAL_QUERYNAME_PROPERTY = 43
    ICAL_RDATE_PROPERTY = 44
    ICAL_RECURRENCEID_PROPERTY = 45
    ICAL_RELATEDTO_PROPERTY = 46
    ICAL_RELCALID_PROPERTY = 47
    ICAL_REPEAT_PROPERTY = 48
    ICAL_REQUESTSTATUS_PROPERTY = 49
    ICAL_RESOURCES_PROPERTY = 50
    ICAL_RRULE_PROPERTY = 51
    ICAL_SCOPE_PROPERTY = 52
    ICAL_SEQUENCE_PROPERTY = 53
    ICAL_STATUS_PROPERTY = 54
    ICAL_SUMMARY_PROPERTY = 55
    ICAL_TARGET_PROPERTY = 56
    ICAL_TIMEFORMAT_PROPERTY = 57
    ICAL_TRANSP_PROPERTY = 58
    ICAL_TRIGGER_PROPERTY = 59
    ICAL_TZID_PROPERTY = 60
    ICAL_TZNAME_PROPERTY = 61
    ICAL_TZOFFSETFROM_PROPERTY = 62
    ICAL_TZOFFSETTO_PROPERTY = 63
    ICAL_TZURL_PROPERTY = 64
    ICAL_UID_PROPERTY = 65
    ICAL_URL_PROPERTY = 66
    ICAL_VERSION_PROPERTY = 67
    ICAL_X_PROPERTY = 68
    ICAL_XLICCLASS_PROPERTY = 69
    ICAL_XLICCLUSTERCOUNT_PROPERTY = 70
    ICAL_XLICERROR_PROPERTY = 71
    ICAL_XLICMIMECHARSET_PROPERTY = 72
    ICAL_XLICMIMECID_PROPERTY = 73
    ICAL_XLICMIMECONTENTTYPE_PROPERTY = 74
    ICAL_XLICMIMEENCODING_PROPERTY = 75
    ICAL_XLICMIMEFILENAME_PROPERTY = 76
    ICAL_XLICMIMEOPTINFO_PROPERTY = 77
    ICAL_NO_PROPERTY = 78
  end

  struct IcalProperty
    id : LibC::Char[5]
    kind : IcalPropertyKind
    x_name : LibC::Char*
    parameters : PVLList
    parameter_iterator : PVLElem
    value : IcalValue*
    parent : IcalComponent*
  end
end
